#+title: Blog Generator
#+author: Camilla A.


Just a simple translator, a markup language called camarkup to HTML.
I'm writing this specifically for usage on my own website's blog -- I can't promise It'll work for you, but feel free to use/fork it if you think it will :3 .

Now you may be saying "why are you making this, HTML is easy to write, and you use GNU Emacs with Org Mode anyway, which can be translated to HTML!".
However, I feel like Org's main strength is that it's just *plain text* -- yes it is beautiful, and extremely efficient because of this, but it can make translation into a more structured language like HTML a bit weird.
I also have very strong feelings about how I want it to look, and with some CSS things I want, and some skimming of Org's and Pandoc's docs, I felt this would be a bit easier.
And most importantly by a while, I <3 programming in Clojure, and if I can find an excuse to, I will.

* Camarkup Spec
The spec for camarkup is [[file:doc/markup.org][here]].

* Building and Usage
You'll need:
- [[https://leiningen.org/][Leiningen]]
- The JVM (to run the uberjar)

Then, it's as simple as cloning the directory, and running ~lein uberjar~ to get an uberjar.
I'd recommend however, that you run ~lein test~ before this, to ensure that I haven't pushed some breaking change into the master branch.

There's a GNU Emacs mode for camarkup, [[file:camarkup-mode.el][just here]].
Documentation for it is found [[file:doc/camarkup-mode.org][here]].
